export type TableEntry = { input: string; output: string; nextInput?: string };
export type RomanTable = TableEntry[];

/**
 * 文字列に該当するルールを検索する
 */
function searchEntry(text: string): TableEntry | undefined {
  return romanTable.find((entry) => entry.input === text);
}

/**
 * ローマ字を変換する
 */
function convertRoman(text: string): string {
  const rule = searchEntry(text);
  if (rule === undefined) return text;
  return rule.output;
}

/**
 * inputがprefixで始まるものを検索する
 */
function searchEntriesByPrefix(prefix: string): TableEntry[] {
  return romanTable.filter((entry) => entry.input.startsWith(prefix));
}

/**
 * ローマ字の文字列を、ひらがなに変換する
 */
export function convert(roman: string): string {
  let hiragana = "";
  let buffer = "";
  for (let i = 0; i < roman.length; i++) {
    buffer += roman[i];

    const result = convertBuffer(buffer);
    hiragana += result.output;
    buffer = result.buffer;
  }
  return hiragana;
}

export function convertBuffer(buffer: string): {
  buffer: string;
  output: string;
} {
  const entry = searchEntry(buffer);
  const prefixEntries = searchEntriesByPrefix(buffer);

  if (prefixEntries.length >= 2) {
    // バッファに対する（将来的なものも含む）変換候補が複数ある場合は、変換を保留する
    // 例: buffer=nのとき、nかnnかnaか分からないので保留する
    return { buffer, output: "" };
  } else {
    if (entry) {
      // 変換ルールが1つしかない場合、そのルールを使って変換する
      return {
        output: entry.output,
        buffer: entry.nextInput ? entry.nextInput : "",
      };
    } else {
      // 変換ルールがない場合、バッファはこれから変換される可能性はないので、区切って変換を完了させる
      // |buffer|-1文字と、1文字の2つに分けて変換すればいいっぽい

      const left = buffer.slice(0, buffer.length - 1);
      const right = buffer.slice(buffer.length - 1);

      // 左半分を変換する。本当は右半分も変換して、変換できなかった場合はバッファに入れる必要がある。
      // ここで変換していないのは、ローマ字には1文字で変換されるものがaiueoしかなく、
      // アルファベットの入力のみであれば他の文字+aiueoは全てルールに従って変換されるため。
      // 例えば記号も入力する場合は、";a"などを";あ"に変換する必要があるので、ここで変換が必要。
      // 他にも、例えば"na"→"な"というルールがなければ、"na"をここで"んあ"に変換する必要がある。
      return { output: convertRoman(left), buffer: right };
    }
  }
}

export const romanTable: RomanTable = [
  { input: "-", output: "ー" },
  { input: "~", output: "〜" },
  { input: ".", output: "。" },
  { input: ",", output: "、" },
  { input: "z/", output: "・" },
  { input: "z.", output: "…" },
  { input: "z,", output: "‥" },
  { input: "zh", output: "←" },
  { input: "zj", output: "↓" },
  { input: "zk", output: "↑" },
  { input: "zl", output: "→" },
  { input: "z-", output: "〜" },
  { input: "z[", output: "『" },
  { input: "z]", output: "』" },
  { input: "[", output: "「" },
  { input: "]", output: "」" },
  { input: "va", output: "ゔぁ" },
  { input: "vi", output: "ゔぃ" },
  { input: "vu", output: "ゔ" },
  { input: "ve", output: "ゔぇ" },
  { input: "vo", output: "ゔぉ" },
  { input: "vya", output: "ゔゃ" },
  { input: "vyi", output: "ゔぃ" },
  { input: "vyu", output: "ゔゅ" },
  { input: "vye", output: "ゔぇ" },
  { input: "vyo", output: "ゔょ" },
  { input: "qq", output: "っ", nextInput: "q" },
  { input: "vv", output: "っ", nextInput: "v" },
  { input: "ll", output: "っ", nextInput: "l" },
  { input: "xx", output: "っ", nextInput: "x" },
  { input: "kk", output: "っ", nextInput: "k" },
  { input: "gg", output: "っ", nextInput: "g" },
  { input: "ss", output: "っ", nextInput: "s" },
  { input: "zz", output: "っ", nextInput: "z" },
  { input: "jj", output: "っ", nextInput: "j" },
  { input: "tt", output: "っ", nextInput: "t" },
  { input: "dd", output: "っ", nextInput: "d" },
  { input: "hh", output: "っ", nextInput: "h" },
  { input: "ff", output: "っ", nextInput: "f" },
  { input: "bb", output: "っ", nextInput: "b" },
  { input: "pp", output: "っ", nextInput: "p" },
  { input: "mm", output: "っ", nextInput: "m" },
  { input: "yy", output: "っ", nextInput: "y" },
  { input: "rr", output: "っ", nextInput: "r" },
  { input: "ww", output: "っ", nextInput: "w" },
  { input: "www", output: "w", nextInput: "ww" },
  { input: "cc", output: "っ", nextInput: "c" },
  { input: "kya", output: "きゃ" },
  { input: "kyi", output: "きぃ" },
  { input: "kyu", output: "きゅ" },
  { input: "kye", output: "きぇ" },
  { input: "kyo", output: "きょ" },
  { input: "gya", output: "ぎゃ" },
  { input: "gyi", output: "ぎぃ" },
  { input: "gyu", output: "ぎゅ" },
  { input: "gye", output: "ぎぇ" },
  { input: "gyo", output: "ぎょ" },
  { input: "sya", output: " しゃ" },
  { input: "syi", output: "しぃ" },
  { input: "syu", output: "しゅ" },
  { input: "sye", output: "しぇ" },
  { input: "syo", output: "しょ" },
  { input: "sha", output: "しゃ" },
  { input: "shi", output: "し" },
  { input: "shu", output: "しゅ" },
  { input: "she", output: "しぇ" },
  { input: "sho", output: "しょ" },
  { input: "zya", output: "じゃ" },
  { input: "zyi", output: "じぃ" },
  { input: "zyu", output: "じゅ" },
  { input: "zye", output: "じぇ" },
  { input: "zyo", output: "じょ" },
  { input: "tya", output: "ちゃ" },
  { input: "tyi", output: "ちぃ" },
  { input: "tyu", output: "ちゅ" },
  { input: "tye", output: "ちぇ" },
  { input: "tyo", output: "ちょ" },
  { input: "cha", output: "ちゃ" },
  { input: "chi", output: "ち" },
  { input: "chu", output: "ちゅ" },
  { input: "che", output: "ち ぇ" },
  { input: "cho", output: "ちょ" },
  { input: "cya", output: "ちゃ" },
  { input: "cyi", output: "ちぃ" },
  { input: "cyu", output: "ちゅ" },
  { input: "cye", output: "ちぇ" },
  { input: "cyo", output: "ちょ" },
  { input: "dya", output: "ぢゃ" },
  { input: "dyi", output: "ぢぃ" },
  { input: "dyu", output: "ぢゅ" },
  { input: "dye", output: "ぢぇ" },
  { input: "dyo", output: "ぢょ" },
  { input: "tsa", output: "つぁ" },
  { input: "tsi", output: "つぃ" },
  { input: "tse", output: "つぇ" },
  { input: "tso", output: "つぉ" },
  { input: "tha", output: "てゃ" },
  { input: "thi", output: "てぃ" },
  { input: "t'i", output: "てぃ" },
  { input: "thu", output: "てゅ" },
  { input: "the", output: "てぇ" },
  { input: "tho", output: "てょ" },
  { input: "t'yu", output: "てゅ" },
  { input: "dha", output: "でゃ" },
  { input: "dhi", output: "でぃ" },
  { input: "d'i", output: "でぃ" },
  { input: "dhu", output: "でゅ" },
  { input: "dhe", output: "でぇ" },
  { input: "dho", output: "でょ" },
  { input: "d'yu", output: "でゅ" },
  { input: "twa", output: "とぁ" },
  { input: "twi", output: "とぃ" },
  { input: "twu", output: "とぅ" },
  { input: "twe", output: "とぇ" },
  { input: "two", output: "とぉ" },
  { input: "t'u", output: "とぅ" },
  { input: "dwa", output: "どぁ" },
  { input: "dwi", output: "どぃ" },
  { input: "dwu", output: "どぅ" },
  { input: "dwe", output: "どぇ" },
  { input: "dwo", output: "どぉ" },
  { input: "d'u", output: "どぅ" },
  { input: "nya", output: "にゃ" },
  { input: "nyi", output: "にぃ" },
  { input: "nyu", output: "にゅ" },
  { input: "nye", output: "にぇ" },
  { input: "nyo", output: "にょ" },
  { input: "hya", output: "ひゃ" },
  { input: "hyi", output: "ひぃ" },
  { input: "hyu", output: "ひゅ" },
  { input: "hye", output: "ひぇ" },
  { input: "hyo", output: "ひょ" },
  { input: "bya", output: "びゃ" },
  { input: "byi", output: "びぃ" },
  { input: "byu", output: "びゅ" },
  { input: "bye", output: "びぇ" },
  { input: "byo", output: "びょ" },
  { input: "pya", output: "ぴゃ" },
  { input: "pyi", output: "ぴぃ" },
  { input: "pyu", output: "ぴゅ" },
  { input: "pye", output: "ぴぇ" },
  { input: "pyo", output: "ぴょ" },
  { input: "fa", output: "ふぁ" },
  { input: "fi", output: "ふぃ" },
  { input: "fu", output: "ふ" },
  { input: "fe", output: "ふぇ" },
  { input: "fo", output: "ふぉ" },
  { input: "fya", output: "ふゃ" },
  { input: "fyu", output: "ふゅ" },
  { input: "fyo", output: "ふょ" },
  { input: "hwa", output: "ふぁ" },
  { input: "hwi", output: "ふぃ" },
  { input: "hwe", output: "ふぇ" },
  { input: "hwo", output: "ふぉ" },
  { input: "hwyu", output: "ふゅ" },
  { input: "mya", output: "みゃ" },
  { input: "myi", output: "みぃ" },
  { input: "myu", output: "みゅ" },
  { input: "mye", output: "みぇ" },
  { input: "myo", output: "みょ" },
  { input: "rya", output: "りゃ" },
  { input: "ryi", output: "りぃ" },
  { input: "ryu", output: "りゅ" },
  { input: "rye", output: "りぇ" },
  { input: "ryo", output: "りょ" },
  { input: "n'", output: "ん" },
  { input: "nn", output: "ん" },
  { input: "n", output: "ん" },
  { input: "xn", output: "ん" },
  { input: "a", output: "あ" },
  { input: "i", output: "い" },
  { input: "u", output: "う" },
  { input: "wu", output: "う" },
  { input: "e", output: "え" },
  { input: "o", output: "お" },
  { input: "xa", output: "ぁ" },
  { input: "xi", output: "ぃ" },
  { input: "xu", output: "ぅ" },
  { input: "xe", output: "ぇ" },
  { input: "xo", output: "ぉ" },
  { input: "la", output: "ぁ" },
  { input: "li", output: "ぃ" },
  { input: "lu", output: "ぅ" },
  { input: "le", output: "ぇ" },
  { input: "lo", output: "ぉ" },
  { input: "lyi", output: "ぃ" },
  { input: "xyi", output: "ぃ" },
  { input: "lye", output: "ぇ" },
  { input: "xye", output: "ぇ" },
  { input: "ye", output: "いぇ" },
  { input: "ka", output: "か" },
  { input: "ki", output: "き" },
  { input: "ku", output: "く" },
  { input: "ke", output: "け" },
  { input: "ko", output: "こ" },
  { input: "xka", output: "ヵ" },
  { input: "xke", output: "ヶ" },
  { input: "lka", output: "ヵ" },
  { input: "lke", output: " ヶ" },
  { input: "ga", output: "が" },
  { input: "gi", output: "ぎ" },
  { input: "gu", output: "ぐ" },
  { input: "ge", output: "げ" },
  { input: "go", output: "ご" },
  { input: "sa", output: "さ" },
  { input: "si", output: "し" },
  { input: "su", output: "す" },
  { input: "se", output: "せ" },
  { input: "so", output: "そ" },
  { input: "ca", output: "か" },
  { input: "ci", output: "し" },
  { input: "cu", output: "く" },
  { input: "ce", output: "せ" },
  { input: "co", output: "こ" },
  { input: "qa", output: "くぁ" },
  { input: "qi", output: "くぃ" },
  { input: "qu", output: "く" },
  { input: "qe", output: "くぇ" },
  { input: "qo", output: "くぉ" },
  { input: "kwa", output: "くぁ" },
  { input: "kwi", output: "くぃ" },
  { input: "kwu", output: "くぅ" },
  { input: "kwe", output: "くぇ" },
  { input: "kwo", output: "くぉ" },
  { input: "gwa", output: "ぐぁ" },
  { input: "gwi", output: "ぐぃ" },
  { input: "gwu", output: "ぐぅ" },
  { input: "gwe", output: "ぐぇ" },
  { input: "gwo", output: "ぐぉ" },
  { input: "swa", output: "すぁ" },
  { input: "swi", output: "すぃ" },
  { input: "swu", output: "すぅ" },
  { input: "swe", output: "すぇ" },
  { input: "swo", output: "すぉ" },
  { input: "zwa", output: "ずぁ" },
  { input: "zwi", output: "ずぃ" },
  { input: "zwu", output: "ずぅ" },
  { input: "zwe", output: "ずぇ" },
  { input: "zwo", output: "ずぉ" },
  { input: "za", output: "ざ" },
  { input: "zi", output: "じ" },
  { input: "zu", output: "ず" },
  { input: "ze", output: "ぜ" },
  { input: "zo", output: "ぞ" },
  { input: "ja", output: "じゃ" },
  { input: "ji", output: "じ" },
  { input: "ju", output: "じゅ" },
  { input: "je", output: "じぇ" },
  { input: "jo", output: "じょ" },
  { input: "jya", output: "じゃ" },
  { input: "jyi", output: "じぃ" },
  { input: "jyu", output: "じゅ" },
  { input: "jye", output: "じぇ" },
  { input: "jyo", output: "じょ" },
  { input: "ta", output: "た" },
  { input: "ti", output: "ち" },
  { input: "tu", output: "つ" },
  { input: "tsu", output: "つ" },
  { input: "te", output: "て" },
  { input: "to", output: "と" },
  { input: "da", output: "だ" },
  { input: "di", output: "ぢ" },
  { input: "du", output: "づ" },
  { input: "de", output: "で" },
  { input: "do", output: "ど" },
  { input: "xtu", output: "っ" },
  { input: "xtsu", output: "っ" },
  { input: "ltu", output: "っ" },
  { input: "ltsu", output: "っ" },
  { input: "na", output: "な" },
  { input: "ni", output: "に" },
  { input: "nu", output: "ぬ" },
  { input: "ne", output: "ね" },
  { input: "no", output: "の" },
  { input: "ha", output: "は" },
  { input: "hi", output: "ひ" },
  { input: "hu", output: "ふ" },
  { input: "fu", output: "ふ" },
  { input: "he", output: "へ" },
  { input: "ho", output: "ほ" },
  { input: "ba", output: "ば" },
  { input: "bi", output: "び" },
  { input: "bu", output: "ぶ" },
  { input: "be", output: "べ" },
  { input: "bo", output: "ぼ" },
  { input: "pa", output: "ぱ" },
  { input: "pi", output: "ぴ" },
  { input: "pu", output: "ぷ" },
  { input: "pe", output: "ぺ" },
  { input: "po", output: "ぽ" },
  { input: "ma", output: "ま" },
  { input: "mi", output: "み" },
  { input: "mu", output: "む" },
  { input: "me", output: "め" },
  { input: "mo", output: "も" },
  { input: "xya", output: "ゃ" },
  { input: "lya", output: "ゃ" },
  { input: "ya", output: "や" },
  { input: "wyi", output: "ゐ" },
  { input: "xyu", output: "ゅ" },
  { input: "lyu", output: "ゅ" },
  { input: "yu", output: "ゆ" },
  { input: "wye", output: "ゑ" },
  { input: "xyo", output: "ょ" },
  { input: "lyo", output: "ょ" },
  { input: "yo", output: "よ" },
  { input: "ra", output: "ら" },
  { input: "ri", output: "り" },
  { input: "ru", output: "る" },
  { input: "re", output: "れ" },
  { input: "ro", output: "ろ" },
  { input: "xwa", output: "ゎ" },
  { input: "lwa", output: "ゎ" },
  { input: "wa", output: "わ" },
  { input: "wi", output: "うぃ" },
  { input: "we", output: "うぇ" },
  { input: "wo", output: "を" },
  { input: "wha", output: "うぁ" },
  { input: "whi", output: "うぃ" },
  { input: "whu", output: "う" },
  { input: "whe", output: "うぇ" },
  { input: "who", output: "うぉ" },
];
