import { RomanTable } from "./romantable-type";

export const tukiRomanTable: RomanTable = [
  { input: "q", output: "", nextInput: "そ" },
  { input: "w", output: "", nextInput: "こ" },
  { input: "e", output: "", nextInput: "し" },
  { input: "r", output: "", nextInput: "て" },
  { input: "t", output: "ょ" },
  { input: "a", output: "", nextInput: "は" },
  { input: "s", output: "", nextInput: "か" },
  { input: "d", output: "", nextInput: "★" },
  { input: "f", output: "", nextInput: "と" },
  { input: "g", output: "", nextInput: "た" },
  { input: "z", output: "", nextInput: "す" },
  { input: "x", output: "", nextInput: "け" },
  { input: "c", output: "に" },
  { input: "v", output: "な" },
  { input: "b", output: "", nextInput: "さ" },
  { input: "☆q", output: "ぁ" },
  { input: "☆w", output: "", nextInput: "ひ" },
  { input: "☆e", output: "", nextInput: "ほ" },
  { input: "☆r", output: "", nextInput: "ふ" },
  { input: "☆t", output: "め" },
  { input: "☆a", output: "ぃ" },
  { input: "☆s", output: "", nextInput: "を" },
  { input: "☆d", output: "ら" },
  { input: "☆f", output: "あ" },
  { input: "☆g", output: "", nextInput: "よ" },
  { input: "☆z", output: "ぅ" },
  { input: "☆x", output: "", nextInput: "へ" },
  { input: "☆c", output: "", nextInput: "せ" },
  { input: "☆v", output: "ゅ" },
  { input: "☆b", output: "ゃ" },
  { input: "y", output: "", nextInput: "つ" },
  { input: "u", output: "ん" },
  { input: "i", output: "い" },
  { input: "o", output: "の" },
  { input: "p", output: "り" },
  { input: "[", output: "", nextInput: "ち" },
  { input: "h", output: "", nextInput: "く" },
  { input: "j", output: "う" },
  { input: "k", output: "", nextInput: "☆" },
  { input: "l", output: "゛" },
  { input: ";", output: "", nextInput: "き" },
  { input: "'", output: "れ" },
  { input: "n", output: "っ" },
  { input: "m", output: "る" },
  { input: ",", output: "、" },
  { input: ".", output: "。" },
  { input: "/", output: "゜" },
  { input: "\\", output: "", nextInput: "・" },
  { input: "★y", output: "ぬ" },
  { input: "★u", output: "え" },
  { input: "★i", output: "み" },
  { input: "★o", output: "や" },
  { input: "★p", output: "ぇ" },
  { input: "★[", output: "「" },
  { input: "★h", output: "ま" },
  { input: "★j", output: "お" },
  { input: "★k", output: "も" },
  { input: "★l", output: "わ" },
  { input: "★;", output: "ゆ" },
  { input: "★'", output: "」" },
  { input: "★n", output: "む" },
  { input: "★m", output: "ろ" },
  { input: "★,", output: "ね" },
  { input: "★.", output: "ー" },
  { input: "★/", output: "ぉ" },
  { input: "たl", output: "だ" },
  { input: "ちl", output: "ぢ" },
  { input: "つl", output: "づ" },
  { input: "てl", output: "で" },
  { input: "とl", output: "ど" },
  { input: "かl", output: "が" },
  { input: "きl", output: "ぎ" },
  { input: "くl", output: "ぐ" },
  { input: "けl", output: "げ" },
  { input: "こl", output: "ご" },
  { input: "さl", output: "ざ" },
  { input: "しl", output: "じ" },
  { input: "すl", output: "ず" },
  { input: "せl", output: "ぜ" },
  { input: "そl", output: "ぞ" },
  { input: "たl", output: "だ" },
  { input: "ちl", output: "ぢ" },
  { input: "つl", output: "づ" },
  { input: "てl", output: "で" },
  { input: "とl", output: "ど" },
  { input: "はl", output: "ば" },
  { input: "ひl", output: "び" },
  { input: "ふl", output: "ぶ" },
  { input: "へl", output: "べ" },
  { input: "ほl", output: "ぼ" },
  { input: "は/", output: "ぱ" },
  { input: "ひ/", output: "ぴ" },
  { input: "ふ/", output: "ぷ" },
  { input: "へ/", output: "ぺ" },
  { input: "ほ/", output: "ぽ" },
  // ここは多分使わない
  { input: "★f", output: "", nextInput: "※" },
  { input: "※h", output: "←" },
  { input: "※j", output: "↓" },
  { input: "※k", output: "↑" },
  { input: "※l", output: "→" },
  { input: "※o", output: "ゎ" },
  { input: "※u", output: "", nextInput: "ゑ" },
  { input: "※i", output: "", nextInput: "ゐ" },
  { input: "※@", output: "『" },
  { input: "※:", output: "』" },
  { input: "※[", output: "『" },
  { input: "※]", output: "』" },
  { input: "※.", output: "〜" },
  { input: "ゐl", output: "ヸ" },
  { input: "ゑl", output: "ヹ" },
  { input: "をl", output: "ヺ" },
];

export const tukiRomanTableForRoman: RomanTable = [
  { input: "q", output: "そ" },
  { input: "w", output: "こ" },
  { input: "e", output: "し" },
  { input: "r", output: "て" },
  { input: "t", output: "ょ" },

  { input: "a", output: "は" },
  { input: "s", output: "か" },
  // { input: "d", output: "", nextInput: "★" },
  { input: "f", output: "と" },
  { input: "g", output: "た" },

  { input: "z", output: "す" },
  { input: "x", output: "け" },
  { input: "c", output: "に" },
  { input: "v", output: "な" },
  { input: "b", output: "さ" },

  { input: "kq", output: "ぁ" },
  { input: "kw", output: "ひ" },
  { input: "ke", output: "ほ" },
  { input: "kr", output: "ふ" },
  { input: "kt", output: "め" },

  { input: "ka", output: "ぃ" },
  { input: "ks", output: "を" },
  { input: "kd", output: "ら" },
  { input: "kf", output: "あ" },
  { input: "kg", output: "よ" },

  { input: "kz", output: "ぅ" },
  { input: "kx", output: "へ" },
  { input: "kc", output: "せ" },
  { input: "kv", output: "ゅ" },
  { input: "kb", output: "ゃ" },

  { input: "y", output: "つ" },
  { input: "u", output: "ん" },
  { input: "i", output: "い" },
  { input: "o", output: "の" },
  { input: "p", output: "り" },

  { input: "[", output: "ち" },
  { input: "h", output: "く" },
  { input: "j", output: "う" },
  // { input: "k", output: "", nextInput: "☆" },
  // { input: "l", output: "゛" },
  { input: ";", output: "き" },
  { input: "'", output: "れ" },

  { input: "n", output: "っ" },
  { input: "m", output: "る" },
  { input: ",", output: "、" },
  { input: ".", output: "。" },
  { input: "/", output: "゜" },
  { input: "\\", output: "・" },

  { input: "dy", output: "ぬ" },
  { input: "du", output: "え" },
  { input: "di", output: "み" },
  { input: "do", output: "や" },
  { input: "dp", output: "ぇ" },
  { input: "d[", output: "「" },

  { input: "dh", output: "ま" },
  { input: "dj", output: "お" },
  { input: "dk", output: "も" },
  { input: "dl", output: "わ" },
  { input: "d;", output: "ゆ" },
  { input: "d'", output: "」" },

  { input: "dn", output: "む" },
  { input: "dm", output: "ろ" },
  { input: "d,", output: "ね" },
  { input: "d.", output: "ー" },
  { input: "d/", output: "ぉ" },

  { input: "sl", output: "が" },
  { input: ";l", output: "ぎ" },
  { input: "hl", output: "ぐ" },
  { input: "xl", output: "げ" },
  { input: "wl", output: "ご" },

  { input: "bl", output: "ざ" },
  { input: "el", output: "じ" },
  { input: "zl", output: "ず" },
  { input: "kcl", output: "ぜ" },
  { input: "ql", output: "ぞ" },

  { input: "gl", output: "だ" },
  { input: "[l", output: "ぢ" },
  { input: "yl", output: "づ" },
  { input: "rl", output: "で" },
  { input: "fl", output: "ど" },

  { input: "al", output: "ば" },
  { input: "kwl", output: "び" },
  { input: "krl", output: "ぶ" },
  { input: "kxl", output: "べ" },
  { input: "kel", output: "ぼ" },

  { input: "a/", output: "ぱ" },
  { input: "kw/", output: "ぴ" },
  { input: "kr/", output: "ぷ" },
  { input: "kx/", output: "ぺ" },
  { input: "ke/", output: "ぽ" },
];
